### ISSUE TITLE
Create GitHub Actions to generate the msi installer

### ISSUE THREAD

**Issue by tijcolem** [NREL/gbxml-to-openstudio#117] opened 2022-09-16 19:59 UTC
See https://github.com/Caphyon/advinst-github-action if this can be used to automate the process. 

Also relevant https://www.advancedinstaller.com/user-guide/refresh-synchronized-folder.html

**Comment by MatthewSteen** [comment] 2023-01-30 19:06
Duplicate of #20.

**Closed by MatthewSteen** 2023-01-30 19:06 UTC
